#!/bin/bash

cd /var/mobile/Library/Preferences

plutil -key _NepetaIconState -remove com.apple.springboard.plist || true
plutil -key _GridiculousIconState -remove com.apple.springboard.plist || true
plutil -convert binary1 com.apple.springboard.plist || true
